### ISSUE TITLE
measure DC

### ISSUE THREAD

**Issue by d01cid** [shadow578/homeassistant_sma_data_manager#20]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

need it since the regular sma plugin does not work with a datamanager

### Describe the solution you'd like

like to install your plugin for the sma datamanager and like to measure the dc side of the inverter, such as the Core2 and tripower X

can u please add following:

Measurement.DcMs.Vol[0] ... Measurement.DcMs.Vol[11]
Measurement.DcMs.Amp[0] ... Measurement.DcMs.Amp[11]
Measurement.DcMs.Watt[0] ... Measurement.DcMs.Watt[11]

please, can u have a look and keep me posted.

### Describe alternatives you've considered

reading the inverter trough modbus does not work and/or give wrong results

### Additional context

i appreciated your work, tanx

**Comment by shadow578** [comment]
hi, 
i need some more information to add the channels. 

could you provide a screenshot of the instantaneous values page with a filter set for "Measurement.DcMs.Vol" (and the other three)
The Name, Channel and Current Value fields should be visible.
Example (but this should show values for you): 
![grafik](https://github.com/shadow578/homeassistant_sma_data_manager/assets/52449218/7cbe3767-0d3a-499e-9a98-f8e54e845d04)

please also include some informaton what kind of device thsi data is from. 
Is this a solar inverter?

**Comment by d01cid** [comment]
hi,
this is a screenshot of the SMA  EDMM-10 managing a SMA Tripower Core2 STP 110-60  which has 12 MPPT.
the same is true on the latest SMA Sunny Tripower X. 
with your plugin i like to make a homeassistant dashboard where i can meassure/monitor the DC side of the inverter.
i have allready been poking in your code and found a file custom_components/sma_data_manager/sma/known_channels.py where i add the missing channels without result.
![Screenshot from 2024-01-18 20-30-44](https://github.com/shadow578/homeassistant_sma_data_manager/assets/37050263/1aa3edc8-dffc-45e7-8c9a-07e378c41f33)

**Comment by shadow578** [comment]
>  file custom_components/sma_data_manager/sma/known_channels.py where i add the missing channels without result.

thats the main thing that has to be done, so if that didn't work there might be something more going on... 
Could you share the code you've added to the `known_channels.py` file so i can take a look?

---

on another note, are you able to see & enable the channels in the integration options page? 

![SMA Data Manager Options](https://github.com/shadow578/homeassistant_sma_data_manager/assets/52449218/2cf205ef-033f-4a68-b199-0679b3779d61)

**Comment by d01cid** [comment]
[known_channels.zip](https://github.com/shadow578/homeassistant_sma_data_manager/files/13999405/known_channels.zip)

i have access to a SMA TripowerX, which has 3 MPPT's
i've modified the mentioned file **known_channels.py** with 9 new lines.
i restart ha, but i can't see the new enries in the pulldown menu:
![Screenshot from 2024-01-20 23-41-30](https://github.com/shadow578/homeassistant_sma_data_manager/assets/37050263/c45ff970-933c-47f1-ad91-f591333f27a2)
can u have a loop please?
PS: if needed/usefull, i can give u access to my remote environment.

**Comment by shadow578** [comment]
>  i restart ha, but i can't see the new enries in the pulldown menu:

are you able to scroll down in the list? 
Are there any values for `Measurement.DcMs.Vol[x]`, `Measurement.DcMs.Amp[x]` or `Measurement.DcMs.Watt[x]` in the list?

---

if not, could you add some `print` statement (or similar) before this line: 
https://github.com/shadow578/homeassistant_sma_data_manager/blob/b8bebefb65c929308e23b39cfba19c6d121cd8b5/custom_components/sma_data_manager/config_flow.py#L322

please add print statements to dump both `all_components` and `all_live_data` in a way where the values are visible.
you'll probably have to iterate over the entries with a for loop.

**Comment by d01cid** [comment]
[known_channels.zip](https://github.com/shadow578/homeassistant_sma_data_manager/files/14016600/known_channels.zip)

this is the modified **known_channels.py** file
i'm not a python developper so i can't dump in a way where the values are visible.
can u reproduce the testcase in your environment?
many tanx.

**Comment by d01cid** [comment]
chris,
sorry 2 disturb u, but did u had the chance for testing my modifications yet?
keep me informed please.

**Comment by shadow578** [comment]
Hi @d01cid ,

sorry for the slow response on my end. 

I've since been able to replicate the issue (turns out my PR inverters also report these kind of values).
i've created a PR that should add support for all the measurements you requested in the original issue, plus a few extra ones.

---

it would be very great if you could test the changes on your system before i merge them. 
to do so, please manually clone the repo into the custom_components folder of your homeassistant, selecting the `add/array-channels-support` branch.

**Comment by d01cid** [comment]
like 2 help but don't know what u mean.
i cloned the latest stuff from github but can not see the "add/array-channels-support" branch.
please let me know what 2 do
